import { AlertController, Content, NavController, ViewController } from '../../../../../..';
import { MyCmpTest } from './my-component';
export declare class FirstPage {
    navCtrl: NavController;
    viewCtrl: ViewController;
    alertCtrl: AlertController;
    pushPage: string;
    firstPage: typeof FirstPage;
    title: string;
    pages: Array<number>;
    content: Content;
    myCmp: MyCmpTest;
    canLeave: boolean;
    called: any;
    constructor(navCtrl: NavController, viewCtrl: ViewController, alertCtrl: AlertController);
    ionViewWillLoad(): void;
    ionViewDidLoad(): void;
    ionViewWillEnter(): void;
    ionViewDidEnter(): void;
    ionViewWillLeave(): void;
    ionViewDidLeave(): void;
    ionViewWillUnload(): void;
    ionViewCanLeave(): boolean;
    ionViewCanEnter(): boolean;
    setPages(): void;
    setRoot(): void;
    pushPrimaryHeaderPage(): void;
    pushRedirect(): void;
    pushFullPage(): void;
    pushAnother(): void;
    pushTabsPage(): void;
    quickPush(): void;
    quickPop(): void;
    pop(): void;
    viewDismiss(): void;
    reload(): void;
    scrollToTop(): void;
    scrollToBottom(): void;
}
